"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bvzr6au4@!687p6du0u#$_zxv=exkx8gmrski9x#z&+-19!r)9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'app',
    'site_controller',
    'authentication',
    'data_entry',
    'recommendation_system',

    'payments.apps.PaymentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres.wrvjhptmncjkpkperosh',
        'PASSWORD': 'zdC0ftovLBMBis4N',
        'HOST': 'aws-1-ap-northeast-1.pooler.supabase.com',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ─── Email configuration (add near the bottom of settings.py) ─────────────────
 
# Option A — Console backend (prints OTP to terminal during development)
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
 
# Option B — Real SMTP (e.g. Gmail). Comment out Option A and use this instead:
EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST       = 'smtp.gmail.com'
EMAIL_PORT       = 587
EMAIL_USE_TLS = True      # STARTTLS
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'shovondevnath616@gmail.com'

EMAIL_HOST_PASSWORD = 'ibsppkeusyptzuak'   # Use an App Password, not your real password
DEFAULT_FROM_EMAIL = 'shovondevnath616@gmail.com'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/statics/'
STATICFILES_DIRS = [BASE_DIR / 'statics']


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Supabase Storage (S3-compatible API)
SUPABASE_PROJECT_REF = os.getenv('SUPABASE_PROJECT_REF', 'wrvjhptmncjkpkperosh')
SUPABASE_S3_ENDPOINT = os.getenv(
    'SUPABASE_S3_ENDPOINT',
    'https://wrvjhptmncjkpkperosh.storage.supabase.co/storage/v1/s3',
)

AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_S3_ACCESS_KEY_ID', '2a1aa05311e70dc63fbc9de5b6070271')
AWS_SECRET_ACCESS_KEY = os.getenv(
    'SUPABASE_S3_SECRET_ACCESS_KEY',
    '4ce52901564e95ac9b5100887ac3d71a329c7277cc11a189ce982fc51f8cde7e',
)
AWS_S3_ENDPOINT_URL = SUPABASE_S3_ENDPOINT
AWS_S3_REGION_NAME = os.getenv('SUPABASE_S3_REGION', 'ap-northeast-1')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False


STRIPE_SECRET_KEY = ''
STRIPE_PUBLISHABLE_KEY = 'pk_test_51TY1lSCYulxeZXnZPh0DYyb9QUk1Ykmtg23vpbOQdVNvWtFaGKqweHYG4vuuGN7CNcKxVj3GugTO4bOBYjHFlrPx0007ViML1D'